# Same configuration that run25 but i have changed how i use the dropout in the architecture

contrastive_learning:
  margin: 0.1
  type_of_triplets: 'all'

epochs: 200
batch_size: 5
loader: True

added_features: 2 # The added features to the vector of the nodes. # angle and distance
model_name: "Contrastive_nodes" 
optimizer: "ADAMW"
lr: 0.001
val_size: 0.1

momentum: 0.9
weight_decay: 0.0001

schedule_name: "CosineAnnealingLR"
milestones: [600, 800]
gamma: 0.1
# Values for the CosineAnnealingLR scheduler
T_max: 200
eta_min: 0.00001

Tresh_distance: False
layers_dimensions: [9, 15, 17]
dropout: 0.3
mask_rate: 0.4
concat_hidden: False

activation: "relu"
reduce: "mean"
train_method: "Sub_Graphs_masking_edges"
kmeans_partition: True

pickle_path_train_kmeans: '/home/nbiescas/Desktop/CVC/CVC_internship/PKL_Graphs/Kmeans_dis_ntresh_discrete/train_Kmeans_dis_ntresh_discrete.pkl'
pickle_path_test_kmeans: '/home/nbiescas/Desktop/CVC/CVC_internship/PKL_Graphs/Kmeans_dis_ntresh_discrete/test_Kmeans_dis_ntresh_discrete.pkl'

Dataset_partitions:
  n: 5
  m: 5

network: 
  checkpoint: ~

node_classes: 4
edge_classes: 2

images:
  start: 0
  end: 10


features:
  node: ['Geometric']
  edge: ['distance', 'angle']