epochs: 2000
batch_size: 30
loader: True

model_name: "MaskedGat_contrastive_linegraphs" 
optimizer: "ADAMW"
lr: 0.001
val_size: 0.1

momentum: 0.9
weight_decay: 0.0001

schedule_name: "CosineAnnealingLR"
milestones: [600, 800]
gamma: 0.1
# Values for the CosineAnnealingLR scheduler
T_max: 200
eta_min: 0.00001


activation: "relu"
reduce: "mean"
train_method: "contrastive_training_embeddings"
kmeans_partition: True

train_graphs : '/home/nbiescas/Desktop/CVC/CVC_internship/PKL_Graphs/line_graphs_kmeans_contrastive/train_line_graphs.bin'
test_graphs: '/home/nbiescas/Desktop/CVC/CVC_internship/PKL_Graphs/line_graphs_kmeans_contrastive/test_line_graphs.bin'

Dataset_partitions:
  n: 5
  m: 5

network: 
  checkpoint: ~

freeze_network: False
unfreeze_epoch: -1

node_classes: 2
edge_classes: 2

images:
  start: 0
  end: 10

cfg_edge_predictor:
    in_features: 20
    hidden_dim: 20
    out_classes: 2
    dropout: 0
    edge_pred_features: 14 # Polar coordinates + class probablities for the src and dst nodes

features:
  node: ['Geometric']
  edge: ['distance', 'angle']

in_dim: 11
hidden_dim: 20
num_heads: 4
num_layers: 4
feat_drop: 0.1
attn_drop: 0.2
negative_slope: 0.2
residual: True

mask_rate: 0.2