wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694857703.499296
    t:
      1:
      - 1
      - 55
      - 76
      2:
      - 1
      - 55
      - 76
      3:
      - 1
      - 17
      - 23
      - 37
      4: 3.11.4
      5: 0.15.10
      8:
      - 5
