# Same configuration that run25 but i have changed how i use the dropout in the architecture

epochs: 2000
batch_size: 30
loader: True

model_name: "GAT_contrastive" 
optimizer: "ADAMW"
lr: 0.001
val_size: 0.1

momentum: 0.9
weight_decay: 0.0001

schedule_name: "CosineAnnealingLR"
milestones: [600, 800]
gamma: 0.1
# Values for the CosineAnnealingLR scheduler
T_max: 200
eta_min: 0.00001


activation: "relu"
reduce: "mean"
train_method: "contrastive_training_embeddings"
kmeans_partition: True

train_graphs : '/home/nbiescas/Desktop/CVC/CVC_internship/runs/run42/graphs_contrastive/train_contrastive.bin'
test_graphs: '/home/nbiescas/Desktop/CVC/CVC_internship/runs/run42/graphs_contrastive/test_contrastive.bin'

Dataset_partitions:
  n: 5
  m: 5

network: 
  checkpoint: ~

node_classes: 4
edge_classes: 2

images:
  start: 0
  end: 10


features:
  node: ['Geometric']
  edge: ['distance', 'angle']

in_dim: 17
hidden_dim: 20
num_heads: 4
num_layers: 3
feat_drop: 0.1
attn_drop: 0.1
negative_slope: 0.2
residual: True