## Configuration options to run Autoencoder.py # Changed to weighted loss in the classification task
epochs: 1000
batch_size: 119

model_name: "SELF"
optimizer: "ADAMW"
lr: 0.001
momentum: 0.9
weight_decay: 0.0005

layers_dimensions: [9, 9, 6]
dropout: 0.2
dropedge: 0.0
mask_rate: 0.2
concat_hidden: False

schedule_name: "ReduceLROnPlateau"
reduce: "mean"
train_method: "Sub_Graphs_masking"

pickle_path_train: '/home/nbiescas/Desktop/CVC/CVC_internship/train_graph.pkl'
pickle_path_test: '/home/nbiescas/Desktop/CVC/CVC_internship/test_graph.pkl'

Dataset_partitions:
  n: 5
  m: 5

network: 
  checkpoint: ~

node_classes: 4
edge_classes: 2

images:
  start: 0
  end: 10