## Configuration options to run Autoencoder.py
epochs: 800

model_name: "GAT"
optimizer: "ADAMW"
lr: 0.001
momentum: 0.9
weight_decay: 0.0

layers_dimensions: [9, 9, 6]
dropout: 0.2
dropedge: 0.2
mask_rate: 0.15
concat_hidden: False

schedule_name: "ReduceLROnPlateau"
reduce: "mean"
train_method: "GAT"

network: 
  checkpoint: ~

node_classes: 4
edge_classes: 2

images:
  start: 0
  end: 10