# 
run_name: "run76_new_partitions"

contrastive_learning:
  margin: 1.0
  type_of_triplets: 'all'
  distance_metric: 'CosineSimilarity'

pretrainedWeights: True
norm: 'none'
epochs: 200
batch_size: 4
loader: True

in_dim: 11
out_dim: 14
use_lynorm: True
model_name: "Contrastive_model_edges_features" 
optimizer: "ADAMW"
lr: 0.0001
val_size: 0.1

momentum: 0.9
weight_decay: 0.0001

schedule_name: "CosineAnnealingLR"
milestones: [600, 800]
gamma: 0.1
# Values for the CosineAnnealingLR scheduler
T_max: 200
eta_min: 0.00001

Tresh_distance: False
layers_dimensions: [14, 16, 18]
dropout: 0.3
mask_rate: 0.0
concat_hidden: False

activation: "relu"
reduce: "mean"
train_method: "Sub_Graphs_masking_edges"
kmeans_partition: True

pickle_path_train_kmeans: '/home/nbiescas/Desktop/CVC/CVC_internship/PKL_Graphs/V2_Kmeans_dis_ntresh_discrete/train_Kmeans_dis_ntresh_discrete.pkl'
pickle_path_val_kmeans: '/home/nbiescas/Desktop/CVC/CVC_internship/PKL_Graphs/V2_Kmeans_dis_ntresh_discrete/val_Kmeans_dis_ntresh_discrete.pkl'
pickle_path_test_kmeans: '/home/nbiescas/Desktop/CVC/CVC_internship/PKL_Graphs/V2_Kmeans_dis_ntresh_discrete/test_Kmeans_dis_ntresh_discrete.pkl'

Dataset_partitions:
  n: 5
  m: 5

network: 
  checkpoint: ~

node_classes: 4
edge_classes: 2

images:
  start: 0
  end: 10


features:
  node: ['Geometric']
  edge: ['distance', 'angle']